% Auto-generated by stereoCalibrator app on 07-Feb-2023
%-------------------------------------------------------


% Define images to process
imageFileNames1 = {'/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam1/1.png',...
    '/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam1/33.png',...
    '/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam1/9.png',...
    };
imageFileNames2 = {'/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam2/1.png',...
    '/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam2/33.png',...
    '/home/river/Downloads/calibration_0003-20230207T233516Z-001/calibration_0003/cam2/9.png',...
    };

% Detect calibration pattern in images
detector = vision.calibration.stereo.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames1, imageFileNames2);

% Generate world coordinates for the planar patten keypoints
squareSize = 40;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I2 = imread(imageFileNames2{1});
[J1, J2, reprojectionMatrix] = rectifyStereoImages(I1, I2, stereoParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
% showdemo('DepthEstimationFromStereoVideoExample')
[intrinsicMatrix1,distortionCoefficients1,intrinsicMatrix2,distortionCoefficients2,rotationOfCamera2,translationOfCamera2] = stereoParametersToOpenCV(stereoParams)